### ISSUE TITLE
Nexus not importing head blocker text (Masha) 

### ISSUE THREAD

**Issue by mashathomas** [Microsoft/SqlNexus#52]
The blocker script is showing the text for the headblocker query, but for some reason this data isn't being imported into nexus

**Comment by vikasrana2006** [comment]
For blocking issue it’s not showing blocking tree because we basically pull blocking report using SP DataSet_WaitStats_BlockingChains >  which query vw_BLOCKING_CHAINS  view > which pull data from tbl_HEADBLOCKERSUMMARY table.
So import is failing due to statement text size having lot of space and comments toward the end,  at this point  this looks pretty corner scenario however we will see how best we can handle this scenario in future. If anyone see similar issue then please reopen this and share the repro with me. Thanks for reporting this issue.
