### ISSUE TITLE
Issues with New Memory Error Collectors (continuation of issue #43) (Masha)

### ISSUE THREAD

**Issue by MashaMSFT** [microsoft/SqlNexus#53]
First, as Suresh noted, the new memory collectors are failing to import to SQL Nexus. Additionally...

The new memory output collects SO much data it's difficult to even go through. Can we maybe try to recycle these files as well? Running it for a few hours got me 28gb of data! Which, even with a file splitter, is pretty difficult to read through. Maybe we can also collect less data?

These are super useful:
-- sys.dm_os_memory_objects (total memory by type, >1MB)
-- memory_workingset_trimming
-- query execution memory --
-- proccache_summary

But these are causing so much bloat and (I could definitely be wrong)  but I'm not finding much value in them:
-- dm_os_memory_cache_counters
-- dm_os_memory_clerks
-- dm_os_memory_cache_clock_hands
-- dm_os_memory_cache_hash_tables
-- dm_os_memory_pools

Maybe we can loop these less frequently and/or split them off into a different file?

**Comment by PiJoCoder** [comment]
Finally getting around to this: I bet you were hitting an issue that others reported. The issue is with the way the data is coming in from PSSDIAG and I have filed an issue there. 
Otherwise, we have recently fixed many of the mentioned DMVs not importing - the fix would be in the latest release build https://github.com/microsoft/SqlNexus/releases/tag/7.21.03.26
Thank you.
