### ISSUE TITLE
Request: Copy and pasting from Nexus reports (Masha) 

### ISSUE THREAD

**Issue by MashaMSFT** [microsoft/SqlNexus#59]
So right now, if I want to grab SQL text for a query from nexus, I either have to find the query manually from the nexus database or export the file to excel and copy the text there. 

Is there anyway we could make it so that we could copy text directly from SQL Nexus? I think this would help save engineers a lot of time.

Thank you!!

**Comment by aaa1niepodam** [comment]
Same here +1

**Comment by PiJoCoder** [comment]
Unfortunately, offline SSRS reports (RDLC files) do not allow to copy text from them, by design. If you use SSRS as a web server and the reports display on a web page, the text can be copied then. But currently SQLNexus operates in offline mode.

See https://stackoverflow.com/questions/45117866/enable-copy-paste-for-ssrs-report-in-preview-mode

There is a \Reports folder in SQL Nexus One and it stores all the *.RDLC files. One way you can workaround is to use a full-fledged SSRS server and upload these reports to SSRS server and have those point to the database. Somebody accomplished this I believe with little tweaking of the reports (rename from RDLC to RDL)
