### ISSUE TITLE
Active Cpu consuming queries

### ISSUE THREAD

**Issue by z50ppeti** [microsoft/SqlNexus#60]
Hello,

I have this error while executino this report

my conf is  : sqlexpress 2008 r2
win 7 pro SP1 32 bits

SQLNexus Information: 0 : Drilling through report: C:\Users\pmpetit\SQLNexus.6.0.0.8\Reports\Active Queries_C.rdlc
    DateTime=2017-12-10T17:22:47.7688790Z
SQLNexus Critical: 0 : Exception: 'format' is not a recognized built-in function name.
Incorrect syntax near 'req'.
Incorrect syntax near the keyword 'and'.. Source: .Net SqlClient Data Provider. Stack:    à System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   à System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   à System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   à System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   à System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   à System.Data.SqlClient.SqlDataReader.get_MetaData()
   à System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   à System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   à System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   à System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   à System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   à System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   à System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   à System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   à System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   à System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   à sqlnexus.fmNexus.FixupDataSources(String filename, String reportname, ReportDataSourceCollection datasources, ReportParameterInfoCollection paramc) dans C:\Users\jackli\Documents\GitHub\Sqlnexus\sqlnexus\fmNexus.cs:ligne 1360. InnerException: .
    DateTime=2017-12-10T17:22:50.3040240Z
SQLNexus Information: 0 : rvTemplate_Drillthrough - Done with Drillthrough
    DateTime=2017-12-10T17:22:55.4593189Z
SQLNexus Information: 0 : rvTemplate_Drillthrough - End
    DateTime=2017-12-10T17:22:55.4593189Z
SQLNexus Information: 0 : rvTemplate_Drillthrough - Finally
    DateTime=2017-12-10T17:22:55.4593189Z
SQLNexus Critical: 0 : Exception: Une instance de source de données manque pour la source de données 'DataSet_Running_Queries'.. Source: Microsoft.ReportViewer.WinForms. Stack:    à Microsoft.Reporting.WinForms.ReportViewer.RenderReportWithNewParameters(Int32 pageNumber, PostRenderArgs postRenderArgs). InnerException: .
    DateTime=2017-12-10T17:22:55.4763198Z

**Comment by ram2ybabu** [comment]
I found that following T-SQL query is executed when the report is called. I am not sure if the FORMAT function is due to a different collation . I tested the query on my machine with SQL server 2014 & above but issue is not reproduced.  I believe the query might have already got fixed.  you can open a new issue if you still get the issue with new nexus version. 
T-SQL query : 
select top 20  format(datediff (MI, request_start_time, req.runtime), 'N', 'en-us') 'running_duration_minutes', 
req.request_start_time, 'still running' request_end_time ,
req.request_logical_reads, 
format((req.request_cpu_time/1000.00/60.0), 'N', 'en-us') 'cpu_time_minutes', naq.stmt_text 
from 
(select runtime, session_id, max(request_cpu_time) 'request_cpu_time', min(request_start_time) 'request_start_time', max(request_logical_reads) 'request_logical_reads' 
from tbl_REQUESTS group by runtime, session_id)  req join tbl_NOTABLEACTIVEQUERIES naq on req.session_id = naq.session_id and req.runtime=naq.runtime
where req.runtime =(select max(runtime) from tbl_requests) and naq.runtime =(select max(runtime) from tbl_requests)
order by req.request_cpu_time desc
