### ISSUE TITLE
Make SQL Nexus case-insensitivity aware for case-sensitive servers.

### ISSUE THREAD

**Issue by DanielAdeniji** [microsoft/SqlNexus#61]
Please make sql_nexus database case-insensitive.

Applications fails when SQL Instance is binary or case-sensitive.

It might help for database to be made case-insensitive each time the sql_nexus database is re-created.

**Comment by hacitandogan** [comment]
@Pijocoder , since this is wave 3 , I was checking it.

I believe failures mentioned here related to some of our queries are not really using the same capitalization with the actual object /field names.
When I import against a CS instance , some reports are failing with errors ;

<img width="316" alt="image" src="https://github.com/microsoft/SqlNexus/assets/25321786/28295d59-558e-424d-8b50-8671cc087ec1">

Changing database creation script seems relatively easy but I have 2 questions here ;

1-Having a different collation then system databases  (specially tempdb) , would this change may end up with some collation conflicts in our import or reports ?  (I did not see any in my tests but can I trust that for all datasets and reports ?)

2-What should be the collation to use  (Latin1_General_100_CI_AI  ? )  or is there anything else we should consider ?

**Comment by PiJoCoder** [comment]
> Changing database creation script seems relatively easy but I have 2 questions here ;
> 
> 1-Having a different collation then system databases (specially tempdb) , would this change may end up with some collation conflicts in our import or reports ? (I did not see any in my tests but can I trust that for all datasets and reports ?)
> 
> 2-What should be the collation to use (Latin1_General_100_CI_AI ? ) or is there anything else we should consider ?

@hacitandogan, thanks. Are you thinking of actually making the database collation case insensitive and then the rest of it will flow from there? Then table and column names won't cause issues due to imprecise choices of case, regardless of case sensitivity or accent sensitivity on the server. I think that's a good approach to solve it globally, for the most part.

1. Yes, it would cause collation conflicts. then we can use the [COLLATE database_default](https://learn.microsoft.com/en-us/sql/t-sql/statements/collations?view=sql-server-ver16#:~:text=database_default%20Causes%20the%20COLLATE%20clause%20to%20inherit%20the%20collation%20of%20the%20current%20database.) for thos instances - hopefully not many of them. I am aware of one report that uses table variables (which use tempdb of course) - the main front one. And I think just found one or two more. There are probably more with temp tables:

- https://github.com/microsoft/SqlNexus/blob/3304546e05fb7ff50934fd2b16beff9d16151d63/NexusReports_bak/SQL%20Perf%20Main.rdl#L19
- https://github.com/microsoft/SqlNexus/blob/3304546e05fb7ff50934fd2b16beff9d16151d63/NexusReports/Query_Store_Details_C.rdl#L350
- https://github.com/microsoft/SqlNexus/blob/3304546e05fb7ff50934fd2b16beff9d16151d63/NexusReports/Linux_Perfmon_C.rdl#L172
- https://github.com/microsoft/SqlNexus/blob/3304546e05fb7ff50934fd2b16beff9d16151d63/NexusReports/Spinlock%20Details_C.rdl#L218
- https://github.com/microsoft/SqlNexus/blob/3304546e05fb7ff50934fd2b16beff9d16151d63/NexusReports_bak/Perfmon_C.rdl#L172
- https://github.com/microsoft/SqlNexus/blob/3304546e05fb7ff50934fd2b16beff9d16151d63/NexusReports/Spinlock%20Stats_C.rdl#L234
- https://github.com/microsoft/SqlNexus/blob/3304546e05fb7ff50934fd2b16beff9d16151d63/NexusReports/Spinlock%20Details_C.rdl#L218

And then, there's the entire PerfStatsAnalysis.sql script, which is full of temp tables. For those we need to consider the COLLATE database_default

https://github.com/microsoft/SqlNexus/blob/3304546e05fb7ff50934fd2b16beff9d16151d63/sqlnexus/PerfStatsAnalysis.sql

2- We can probably consider `SQL_Latin1_General_CP1_CI_AI` as this is a slight variation of the default collation that Setup offers and many people choose to go with. It is a SQL collation. So your recommendation of `Latin1_General_100_CI_AI` might be a better choice.

**Comment by hacitandogan** [comment]
this is fixed., closing.
