### ISSUE TITLE
SQLNexus - Data Import Message

### ISSUE THREAD

**Issue by cdnusr** [microsoft/SqlNexus#63]
Message: "You have captured both trace and xeven files. import will fail! Please remove one of them before importing."

Why is this an issue? 
Is there a fix? If not, what is the best workaround?

**Comment by PiJoCoder** [comment]
Thanks for your questions. We apologize for a very long delay. 
The above error message is an issue because Trace and Xevent files capture the same information via PSSDIAG. And when you import it, this information gets written into the same table. Therefore it makes no sense to record the same set of events twice in the tables. This will render the analysis less useful and inaccurate. For example in ReadTrace.tblBatches table the following set of events get recorded

SQLBatch Starting:  SELECT * FROM SYS.DATABASES   , SPID = 57
SQLBatch Completed:  SELECT * FROM SYS.DATABASES ,  SPID = 57

It would not be useful to record this information twice in the same table - one coming from Xevents and one coming from Traces - it is duplication.
Also, the executable that imports Trace and Xevent data which SQL Nexus launches - ReadTrace.exe - will look for one set of data or the other. If it finds both, it does not know which one to process and will raise this error for you. 
Finally, for the same reason listed above it is not useful to collect both traces at the same time - duplicate info, double the disk space, etc.

**Solution:**
1. Easiest is only collect one set of traces - Xevents OR Traces
2. If the data is already collected and exist in the same \output folder, you can easily just take the one set (e.g. *.trc) files and move them to a sub-folder you created (e.g. \output\traces). Then when you run SQL Nexus, only the Xevent .XEL files will be discovered and successfully imported.
