### ISSUE TITLE
FileNotFoundException on startup

### ISSUE THREAD

**Issue by phillsteele** [microsoft/SqlNexus#74]
On connecting to a local database just after startup I received a FileNotFoundException.

I had to resolve this by installing the RML Utilities for SQL Server.  Note that Azure Support requested I install this tool to help analyse an issue with SQL Azure.

![untitled](https://user-images.githubusercontent.com/27690630/46401659-9a21e580-c6f5-11e8-9864-f5b349038bea.png)

**Comment by PiJoCoder** [comment]
Thank you for reporting. Yes, we have now fixed this issue and will be publishing a build of this soon. Fixed in https://github.com/microsoft/SqlNexus/commit/0f3b22e54b025a90903192fa5b0ab56507c1d2a3#diff-4ff6d2656b901aee0c15cd03881cc107d6d4bc2edd437ce084b4991f367311c5 

But indeed ReadTrace (RML Utilities) is used by SQL nexus to import Xevent or SQL Trace data.
We have also now added a new powershell file that will download and install these prerequisites automatically.
https://github.com/microsoft/SqlNexus/commit/a4c18590c5ad2a030c40a6d05557db8e7d32d56a
