### ISSUE TITLE
Update Rowset Importer for new tables added to PSSDIAG custom scripts

### ISSUE THREAD

**Issue by suresh-kandoth** [microsoft/SqlNexus#89]

**Comment by PiJoCoder** [comment]
Fixed by adding these for now.



tbl_dm_os_loaded_modules
tbl_dm_OS_Schedulers_Snapshot
tbl_StartupParameters
tbl_dm_os_memory_pools
tbl_dm_os_memory_objects
tbl_dm_os_ring_buffers_mem
tbl_Query_Execution_Memory
tbl_dm_os_loaded_modules (nonMicrosoft)
sys.dm_os_sys_info

cda451ebab94b8ee3f438448779f7a8c89f6e383
271d95f48805ae8437a23201e1bb43c8b4aa949a
32a72510cce1a05c693af057962b505869a5834c
cda451ebab94b8ee3f438448779f7a8c89f6e383
271d95f48805ae8437a23201e1bb43c8b4aa949a
32a72510cce1a05c693af057962b505869a5834c
Perhaps best is to file individual issues for new ones as they are discovered/encountered in the future
